"""add prices fix stock unique add shipment_link

Revision ID: 0462163d44a9
Revises: 92b0c208c1d3
Create Date: 2026-05-22 18:04:48.476199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0462163d44a9'
down_revision: Union[str, None] = '92b0c208c1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
