"""add purchase_price and sale_price to products

Revision ID: 0a94ee8abd17
Revises: 45abca8d5fec
Create Date: 2026-05-22 15:14:49.838624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a94ee8abd17'
down_revision: Union[str, None] = '45abca8d5fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
