"""add warehouse documents and stock tables

Revision ID: 3b133bbe31ef
Revises: e0d2a409a0f3
Create Date: 2026-05-21 05:21:03.427486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b133bbe31ef'
down_revision: Union[str, None] = 'e0d2a409a0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_number', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('RECEIVE', 'SHIP', 'TRANSFER', 'ADJUST', name='doctype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='docstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_number')
    )
    op.create_index(op.f('ix_warehouse_documents_id'), 'warehouse_documents', ['id'], unique=False)
    op.create_table('document_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('from_cell_id', sa.Integer(), nullable=True),
    sa.Column('to_cell_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['warehouse_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_items_id'), 'document_items', ['id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_document_items_id'), table_name='document_items')
    op.drop_table('document_items')
    op.drop_index(op.f('ix_warehouse_documents_id'), table_name='warehouse_documents')
    op.drop_table('warehouse_documents')
    # ### end Alembic commands ###
