"""add rbac user roles

Revision ID: 3bb961b2d1c7
Revises: 740529ad5170
Create Date: 2026-05-21 18:33:14.875762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb961b2d1c7'
down_revision: Union[str, None] = '740529ad5170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ADMIN', 'WAREHOUSE_MANAGER', 'WAREHOUSE_WORKER', 'CLIENT', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'WAREHOUSE_MANAGER', 'WAREHOUSE_WORKER', 'CLIENT', name='userrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
