"""add prices and fix models

Revision ID: 45abca8d5fec
Revises: b774f9f33df8
Create Date: 2026-05-22 14:58:58.248109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45abca8d5fec'
down_revision: Union[str, None] = 'b774f9f33df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('order_items', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('orders', sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('orders', 'comment',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('products', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.add_column('stocks', sa.Column('cell_id', sa.Integer(), nullable=True))
    op.add_column('stocks', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stocks', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('stocks', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('stocks_product_id_key', 'stocks', type_='unique')
    op.create_index(op.f('ix_stocks_cell_id'), 'stocks', ['cell_id'], unique=False)
    op.create_index(op.f('ix_stocks_product_id'), 'stocks', ['product_id'], unique=False)
    op.create_unique_constraint('uq_stock_product_cell', 'stocks', ['product_id', 'cell_id'])
    op.create_foreign_key(None, 'stocks', 'cells', ['cell_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.drop_constraint('uq_stock_product_cell', 'stocks', type_='unique')
    op.drop_index(op.f('ix_stocks_product_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_cell_id'), table_name='stocks')
    op.create_unique_constraint('stocks_product_id_key', 'stocks', ['product_id'])
    op.alter_column('stocks', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('stocks', 'last_updated')
    op.drop_column('stocks', 'cost_price')
    op.drop_column('stocks', 'cell_id')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.alter_column('products', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('products', 'sale_price')
    op.drop_column('products', 'purchase_price')
    op.drop_column('products', 'description')
    op.alter_column('orders', 'comment',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('orders', 'total_cost')
    op.alter_column('order_items', 'total_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
