"""add shipment_doc_id to orders

Revision ID: 92b0c208c1d3
Revises: 9a79d5669069
Create Date: 2026-05-22 17:28:22.969147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b0c208c1d3'
down_revision: Union[str, None] = '9a79d5669069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipment_doc_id', sa.Integer(), nullable=True))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('orders', 'comment',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'orders', 'warehouse_documents', ['shipment_doc_id'], ['id'])
    op.drop_column('orders', 'total_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'comment',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('orders', 'shipment_doc_id')
    # ### end Alembic commands ###
