"""add prices and fix stock logic

Revision ID: 9a79d5669069
Revises: 0a94ee8abd17
Create Date: 2026-05-22 16:28:45.959412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a79d5669069'
down_revision: Union[str, None] = '0a94ee8abd17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_barcode', table_name='products')
    op.drop_index('ix_products_category', table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    op.create_index('ix_products_barcode', 'products', ['barcode'], unique=False)
    # ### end Alembic commands ###
