"""add archived_at to products

Revision ID: 9e693bf8b85f
Revises: a73165366255
Create Date: 2026-06-08 20:37:32.494514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e693bf8b85f'
down_revision: Union[str, None] = 'a73165366255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('warehouse_documents', 'type',
               existing_type=postgresql.ENUM('receive', 'ship', 'transfer', 'adjust', name='doctype'),
               nullable=False,
               existing_server_default=sa.text("'receive'::doctype"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouse_documents', 'type',
               existing_type=postgresql.ENUM('receive', 'ship', 'transfer', 'adjust', name='doctype'),
               nullable=True,
               existing_server_default=sa.text("'receive'::doctype"))
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'archived_at')
    # ### end Alembic commands ###
