"""update_move_to_transfer_enum

Revision ID: a73165366255
Revises: 32202f05191a
Create Date: 2026-06-06 02:39:53.433022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73165366255'
down_revision: Union[str, None] = '32202f05191a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'document_items', 'cells', ['from_cell_id'], ['id'])
    op.create_foreign_key(None, 'document_items', 'cells', ['to_cell_id'], ['id'])
    op.create_foreign_key(None, 'document_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'warehouse_documents', 'users', ['operator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse_documents', type_='foreignkey')
    op.drop_constraint(None, 'document_items', type_='foreignkey')
    op.drop_constraint(None, 'document_items', type_='foreignkey')
    op.drop_constraint(None, 'document_items', type_='foreignkey')
    # ### end Alembic commands ###
