"""fix inventory fields

Revision ID: ece911614e35
Revises: 385335911607
Create Date: 2026-06-22 16:14:26.676246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece911614e35'
down_revision: Union[str, None] = '385335911607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('inventories', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('inventories', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inventories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inventory_records', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('inventory_records', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('inventory_records', 'planned_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory_records', 'actual_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_records', 'actual_qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory_records', 'planned_qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('inventory_records', 'created_at')
    op.drop_column('inventory_records', 'comment')
    op.drop_column('inventories', 'updated_at')
    op.drop_column('inventories', 'completed_at')
    op.drop_column('inventories', 'comment')
    op.drop_column('inventories', 'category')
    # ### end Alembic commands ###
