"""Add order approval status and delivery fields

Revision ID: efdb71286585
Revises: 9e693bf8b85f
Create Date: 2026-06-21 00:14:59.101765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdb71286585'
down_revision: Union[str, None] = '9e693bf8b85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_address', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('delivery_method', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('pickup_point_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('client_phone', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('client_email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'client_email')
    op.drop_column('orders', 'client_phone')
    op.drop_column('orders', 'pickup_point_id')
    op.drop_column('orders', 'delivery_method')
    op.drop_column('orders', 'delivery_address')
    # ### end Alembic commands ###
